admin_dashboard:
    path:     / 
    defaults: { _controller: ReunionBundle:Admin:index }
    
_add_event:
    path:   /addEvent
    defaults: { _controller: ReunionBundle:Admin:addEvent }

_edit_event:
    path:   /editEvent/{id}
    defaults: { _controller: ReunionBundle:Admin:editEvent }
 
_list_event:
    path:   /listEvent
    defaults: { _controller: ReunionBundle:Admin:listEvent }

_event_detail:
    path:   /event/{id}
    defaults: { _controller: ReunionBundle:Admin:eventDetail }

_event_list_question:
    path:   /event/{id}/list-question/
    defaults: { _controller: ReunionBundle:Admin:eventListQuestion }    
    
_cloturer_event:
    path:  /cloturerEvent/{id}
    defaults: { _controller: ReunionBundle:Admin:cloturerEvent }
    requirements:
        id:     \d+
    options:
        expose: true

_ouvire_event:
    path:  /ouvrireEvent/{id}
    defaults: { _controller: ReunionBundle:Admin:ouvrireEvent }
    requirements:
        id:         \d+
    options:
        expose: true
        
_delete_event:
    path:  /deleteEvent/{id}
    defaults: { _controller: ReunionBundle:Admin:deleteEvent }
    requirements:
        id:         \d+
    options:
        expose: true

_load_question_json:
    path:   /loadquestion/{id}
    defaults: { _controller : ReunionBundle:Admin:loadQuestionJson }
    options:
        expose: true
        
_check_errors_event:
    path:       /checkErrors
    defaults:   {_controller: ReunionBundle:Admin:ckechErrors }
    options:
        expose: true

_focus_question:
    path:       /focusQuestion
    defaults:   { _controller: ReunionBundle:Admin:focusQuestion }
    options:
        expose: true

_delete_question:
    path:       /deleteQuestion/{id}
    defaults:   { _controller: ReunionBundle:Question:deleteQuestion }
    requirements:
        id:     \d+
    options:
        expose: true 
        
_modification_question:
    path:       /modifierQuestion/{id}
    defaults:   { _controller: ReunionBundle:Admin:modificationQuestion }
    requirements:
        id:     \d+
    options:
        expose: true
        
_save_modification_question:
    path:       /saveModifierQuestion/
    defaults:   { _controller: ReunionBundle:Admin:saveModificationQuestion }
    options:
        expose: true        

_list_commentaire:
    path:       /{id}/listCommentaire/
    defaults:  { _controller: ReunionBundle:Admin:questionListCommentaire }
    requirements:
        id:     \d+
    options:
        expose: true

_list_reponses:
    path:       /{id}/listReponses/
    defaults:  { _controller: ReunionBundle:Admin:commentaireListReponse }
    requirements:
        id:     \d+
    options:
        expose: true

_load_commentaire_json:
    path:       /loadcommentaire/{id}
    defaults:  { _controller: ReunionBundle:Admin:loadCommentaireJson }
    requirements:
        id:     \d+
    options:
        expose: true

_load_reponse_json:
    path:       /loadreponse/{id}
    defaults:  { _controller: ReunionBundle:Admin:loadReponsesJson }
    requirements:
        id:     \d+
    options:
        expose: true

_delete_commentaire:
    path:       /deleteCommentaire/{id}
    defaults:   {_controller: ReunionBundle:Commentaire:deleteCommentaire }
    requirements:
        id:     \d+
    options:
        expose: true

_modification_commentaire:
    path:       /modifierCommentaire/{id}
    defaults:   { _controller: ReunionBundle:Admin:modificationCommentaire }
    requirements:
        id:     \d+
    options:
        expose: true
        
_save_modification_commentaire:
    path:       /saveModifierCommentaire/
    defaults:   { _controller: ReunionBundle:Admin:saveModificationCommentaire }
    options:
        expose: true
   
